### ISSUE TITLE
Safari - TypeError: files.map is not a function

### ISSUE THREAD

**Issue by krestaino** [rowanwins/vue-dropzone#292]
Hello!

There's a bug with adding files in Safari and IE that was fixed with dropzone 5.3.0. Can this repo be updated?

More info here:

https://github.com/enyo/dropzone/issues/1640
https://gitlab.com/meno/dropzone/issues/66
https://gitlab.com/meno/dropzone/merge_requests/31

**Comment by vrajroham** [comment]
Thanks for reminding @krestaino . I'll look into this and will try to update the component ASAP. I'll confirm here once done.

Happy Coding..

**Comment by krestaino** [comment]
Awesome, thank you!

**Comment by rheemy** [comment]
Hey @vrajroham! I've been looking into this within my own project and [this fix](https://gitlab.com/meno/dropzone/merge_requests/31) (implemented on dropzone 12 days ago) works in the same way. I've tested on Safari v11, IE10 and IE11. :)

**Comment by bborn** [comment]
+1 any progress on this?

**Comment by vrajroham** [comment]
Apologize for inconvenience and late arrival @krestaino and all. I have updated code dependency and publishing updated version to npm. Once done I'll update here.

Thanks

**Comment by vrajroham** [comment]
Updated component is published on npm under tag `v3.0.5`, also you can check latest tag here https://github.com/rowanwins/vue-dropzone/releases/tag/v3.0.5

Thanks @krestaino for reporting the issue.

**Comment by kife-design** [comment]
I'm afraid the problem still exists. With the latest version it's still not possible to drag files in safari.

**Comment by vrajroham** [comment]
Open http://www.dropzonejs.com/#try-it-out in Safari. Try drag and drop on this link. Let me know whether it works.

**Comment by rheemy** [comment]
Testing drag on safari v11.03 worked :)

**Comment by kife-design** [comment]
It works on the page you provided.
The demo on the vue-dropzone site does not work (dunno if that is also the latest version.)
I'll do some more testing

**Comment by mcwanek** [comment]
Dropzone was updated to today to v5.4.0 to fix the issues with safari and IE11: https://gitlab.com/meno/dropzone/blob/master/CHANGELOG.md#anchor-540

Should only need a version bump in this project's package.json to get up to date.

**Comment by vrajroham** [comment]
Thanks for reporting! I'll update in component in sometime.

**Comment by mcwanek** [comment]
Much appreciated. I've got an enterprise-level project that's been on 
hold pending the dropzone fixes, now just need a bump on this project 
and I think we'll be able to move forward.

Thanks again!

**Comment by vrajroham** [comment]
@mcwanek Update component has been released, hopefully it helps you.
 
> For latest release pull latest release [3.0.6](https://github.com/rowanwins/vue-dropzone/releases/tag/v3.0.6) from npm.

**Comment by mcwanek** [comment]
Seems to be working now with Safari. Thanks for the quick response!
