### ISSUE TITLE
"Remove File" button is hidden behind error message 

### ISSUE THREAD

**Issue by andredarcie** [rowanwins/vue-dropzone#438]
![image](https://user-images.githubusercontent.com/7493330/55100338-691cdf00-50a0-11e9-9001-4faa20d39dd9.png)

**Comment by rowanwins** [comment]
Hi @andredarcie 

I've just published version `3.5.9` which resolves this issue.

Cheers

**Comment by karingula** [comment]
Hi @rowanwins I'm using version `3.6.0` For some reason this problem still persists
